/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ra_in_coat (https://sketchfab.com/ra_in_coat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tulip-flower-8b865189c6ca4013a39cb25076241494
title: Tulip Flower
*/

import { forwardRef, useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import gsap from "gsap";
export const Tulip = forwardRef(function Tulip(props, ref) {
	const group = useRef();
	const tl = useRef();
	const scroll = useScroll();
	const { nodes, materials, animations } = useGLTF("/tulip_flower.glb");
	const { actions } = useAnimations(animations, group);
	useEffect(() => (actions["Growing"].play().paused = true), [actions]);
	useFrame((state, delta) => {
		const action = actions["Growing"];
		// The offset is between 0 and 1, you can apply it to your models any way you like
		const offset = scroll.offset;
		action.time = THREE.MathUtils.damp(
			action.time,
			(action.getClip().duration / 2) * offset * 2,
			500,
			delta,
		);
	});

	return (
		<group
			position={[0, -4, -2]}
			ref={group}
			scale={2}
			{...props}
			dispose={null}
		>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					rotation={[-Math.PI / 2, 0, 0]}
					scale={1.73}
				>
					<group
						name="0d9c74de749045f2abaff19db4b3ebc8fbx"
						rotation={[Math.PI / 2, 0, 0]}
					>
						<group name="Object_2">
							<group name="RootNode">
								<group
									name="Armature"
									rotation={[-Math.PI / 2, 0, 0]}
								>
									<group name="Object_5">
										<primitive object={nodes._rootJoint} />
										<group
											name="Object_48"
											rotation={[-Math.PI / 2, 0, 0]}
										/>
										<skinnedMesh
											name="Object_49"
											geometry={nodes.Object_49.geometry}
											material={materials.M_TulipFlower}
											skeleton={nodes.Object_49.skeleton}
										/>
									</group>
								</group>

								<group
									name="Tulip"
									rotation={[-Math.PI / 2, 0, 0]}
								/>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
});

useGLTF.preload("/tulip_flower.glb");
